// Code generated by counterfeiter. DO NOT EDIT.
package webfakes

import (
	"net/http"
	"sync"

	"github.com/xanderflood/notebook/lib/web"
)

type FakeVarsGetter struct {
	GetStub        func(r *http.Request) map[string]string
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		r *http.Request
	}
	getReturns struct {
		result1 map[string]string
	}
	getReturnsOnCall map[int]struct {
		result1 map[string]string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeVarsGetter) Get(r *http.Request) map[string]string {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		r *http.Request
	}{r})
	fake.recordInvocation("Get", []interface{}{r})
	fake.getMutex.Unlock()
	if fake.GetStub != nil {
		return fake.GetStub(r)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.getReturns.result1
}

func (fake *FakeVarsGetter) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *FakeVarsGetter) GetArgsForCall(i int) *http.Request {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return fake.getArgsForCall[i].r
}

func (fake *FakeVarsGetter) GetReturns(result1 map[string]string) {
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 map[string]string
	}{result1}
}

func (fake *FakeVarsGetter) GetReturnsOnCall(i int, result1 map[string]string) {
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 map[string]string
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 map[string]string
	}{result1}
}

func (fake *FakeVarsGetter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeVarsGetter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ web.VarsGetter = new(FakeVarsGetter)
